en/content-migrations.md

Craft 3 overrides the insert() and batchInsert() commands to add
a parameter that determines if audit data columns should be automatically
added to $columns.  I've added some documentation for this to hopefully
prevent failed migrations.

Adding documentation for insert() and batchInsert() migration commands

---

en/templating/examples/login-form.md

craft.session.getRememberedUsername() has been deprecated. Use craft.app.user.rememberedUsername instead

replaced craft.session with craft.app.user

---

en/templating/examples/atom-feed.md
en/templating/examples/rss-feed.md

craft.request.getUrl() has been deprecated. Use craft.app.request.absoluteUrl instead.

Change craft.request.getUrl() has been deprecated

---

en/assets-fields.md

Since `first()` is deprecated in Craft 3, in docs should be used the replacement `one()`
https://github.com/craftcms/docs/blob/v3/en/changes-in-craft-3.md#query-methods

Used a deprecated method in docs

---

en/categories-fields.md

Support for treating element queries as if they’re arrays has been deprecated in Craft 3, and will be completely removed in Craft 4.
https://github.com/craftcms/docs/blob/v3/en/changes-in-craft-3.md#treating-queries-as-arrays
Since `first()` is deprecated in Craft 3, in docs should be used the replacement `one()`
https://github.com/craftcms/docs/blob/v3/en/changes-in-craft-3.md#query-methods
Since `order()` is deprecated in Craft 3, in docs should be used the replacement `orderBy()`
https://github.com/craftcms/docs/blob/v3/en/changes-in-craft-3.md#element-queries

Used a deprecated method in Categories Fields docs

---

en/entries-fields.md
en/users-fields.md

Since there are methods that are deprecated, in docs we should use there new replacement.

 Used a deprecated method in some fields docs

---

en/templating/tags/paginate.md

`find()` method is now deprecated in Craft 3, and will be completely removed in Craft 4:
https://github.com/craftcms/docs/blob/v3/en/changes-in-craft-3.md#query-methods

Call of deprecated method.

---

en/matrix-fields.md

I've added the `.all()` and `.one()` methods, replacing `.first()` in the process.

Updated deprecated matrix field code

---

en/templating/examples/user-registration-form.md

Update the documentation to correctly reflect the fact that the variable returned when trying to register a user is `user` not `account`.

Fix mistake in user registration documentation

---

docs/updating-plugins.md

\elements\ should be \events\ in getElementRoute example

Fix namespace path in example

---

docs/changes-in-craft-3.md

Change `public_html` to `web`  because `web` is the default web root folder in Craft 3 and to ensure consistency with the rest of the docs.

Change public_html to web

---

docs/templating/tags/js.md

Looks like there was a copy & paste error between `css` and `js`.

Fixed typo

---

docs/cp-section.md

This feature was missing from the docs. This is especially confusing since the scaffolding created by pluginfactory.io uses the composer.json method for indicating that a plugin should have a control panel section.

Document ability to set 'hasCpSection' in plugin composer.json file

---

docs/upgrade.md

User Photos will not be linked to their respective User Accounts if this step is omitted before running the Craft 2 to Craft 3 database upgrade.

Add step to copy over old User Photos

---

docs/upgrade.md

Add step to copy old custom login page logo and site icon files from craft/storage/rebrand/ over to new project’s storage/rebrand/ directory.

Add step to copy craft/storage/rebrand/ contents

---

docs/upgrade.md

Copy old custom Redactor config files from craft/config/redactor/ over to the new project’s config/redactor/ directory.

Add step to copy over custom Redactor config files

---

docs/templating/tests.md

I received the error Unexpected token "string" of value "craft\\elements\\Entry" ("end of statement block" expected). With the example code, inserting `("craft\\elements\\Entry")` fixed it

fixed syntax error

---

docs/extend/plugin-guide.md

The setting works in root packages only.

No minimum-stability

---

docs/dev/element-queries/README.md

Actually there is no `[ x => y]` Twig syntax. at least when I copy paste your code it throws an Exception `An array element must be followed by a comma. Unexpected token "operator" of value "=" ("punctuation" expected with value ",").`

Fixed Twig syntax

---

docs/templating/forgot-password-form.md

Other documentation such as the password reset file (https://docs.craftcms.com/v2/templating/set-password-form.html) give information about config options for setting the path, whereas this one does not. To save users potentially trying to find out if there is any config for this template, tell them straight away it doesn't exist and this template is only ever linked to where you set it in your templates.
Please re-write in the Craft tone of voice 👍 .

Giving more details about config

---

docs/requirements.md

`DELETE` appears twice; I simply removed the duplicate.

Fix typo in PostgreSQL privilege requirements

---

docs/dev/filters.md

PHP example for the `hash` filter currently uses Craft 2 syntax instead of new Craft 3 syntax.

Fix php example to use Craft 3 syntax

---

docs/table-fields.md

noticed I was getting a deprecation warning when looping through table rows

add '.all()'

---

docs/config/README.md

Changed the env var name to be the same as later in [overriding-volume-settings](https://docs.craftcms.com/v3/config/#overriding-volume-settings).

Unified env var names for assets
